
package org.tempuri.srvIntConsultaSIPOV;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import co.gov.gobiernoenlinea.gel_xml._1_0.schemas.proyectos.minagricultura.sipov.ArrayOfTipoOrden;
import co.gov.gobiernoenlinea.gel_xml._1_0.schemas.proyectos.minagricultura.sipov.TipoOrdenesEnt;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultarOrdenesSIPOVWsServiceSOAP", targetNamespace = "http://minagricultura.gov.co")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    co.gov.gobiernoenlinea.gel_xml._1_0.schemas.proyectos.minagricultura.sipov.ObjectFactory.class,
    org.tempuri.srvIntConsultaSIPOV.ObjectFactory.class
})
public interface ConsultarOrdenesSIPOVWsServiceSOAP {


    /**
     * 
     * @param ordenesEnt
     * @return
     *     returns co.gov.gobiernoenlinea.gel_xml._1_0.schemas.proyectos.minagricultura.sipov.ArrayOfTipoOrden
     */
    @WebMethod(action = "http://minagricultura.gov.co/NewOperation")
    @WebResult(name = "ordenesSal", targetNamespace = "http://www.gobiernoenlinea.gov.co/GEL-XML/1.0/schemas/Proyectos/MinAgricultura/SIPOV", partName = "consultarOrdenesSIPOVResult")
    public ArrayOfTipoOrden consultarOrdenesSIPOV(
        @WebParam(name = "ordenesEnt", targetNamespace = "http://www.gobiernoenlinea.gov.co/GEL-XML/1.0/schemas/Proyectos/MinAgricultura/SIPOV", partName = "ordenesEnt")
        TipoOrdenesEnt ordenesEnt,
        @WebParam(name = "AuthHeader", targetNamespace = "http://www.gobiernoenlinea.gov.co/GEL-XML/1.0/schemas/Proyectos/MinAgricultura/SIPOV", partName = "AuthHeader")
        AuthHeader AuthHeader);

}
