
package org.tempuri.srvIntConsultaSIPOV;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "consultarOrdenesSIPOV", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.30.13.11:8061/Servicios/consultarOrdenesSIPOV.asmx?wsdl")
public class ConsultarOrdenesSIPOV
    extends Service
{

    private final static URL CONSULTARORDENESSIPOV_WSDL_LOCATION;
    private final static WebServiceException CONSULTARORDENESSIPOV_EXCEPTION;
    private final static QName CONSULTARORDENESSIPOV_QNAME = new QName("http://tempuri.org/", "consultarOrdenesSIPOV");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.13.11:8061/Servicios/consultarOrdenesSIPOV.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARORDENESSIPOV_WSDL_LOCATION = url;
        CONSULTARORDENESSIPOV_EXCEPTION = e;
    }

    public ConsultarOrdenesSIPOV() {
        super(__getWsdlLocation(), CONSULTARORDENESSIPOV_QNAME);
    }

    public ConsultarOrdenesSIPOV(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARORDENESSIPOV_QNAME, features);
    }

    public ConsultarOrdenesSIPOV(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARORDENESSIPOV_QNAME);
    }

    public ConsultarOrdenesSIPOV(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARORDENESSIPOV_QNAME, features);
    }

    public ConsultarOrdenesSIPOV(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarOrdenesSIPOV(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultarOrdenesSIPOVWsServiceSOAP
     */
    @WebEndpoint(name = "ConsultarOrdenesSIPOVWsServiceSOAP")
    public ConsultarOrdenesSIPOVWsServiceSOAP getConsultarOrdenesSIPOVWsServiceSOAP() {
        return super.getPort(new QName("http://tempuri.org/", "ConsultarOrdenesSIPOVWsServiceSOAP"), ConsultarOrdenesSIPOVWsServiceSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarOrdenesSIPOVWsServiceSOAP
     */
    @WebEndpoint(name = "ConsultarOrdenesSIPOVWsServiceSOAP")
    public ConsultarOrdenesSIPOVWsServiceSOAP getConsultarOrdenesSIPOVWsServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ConsultarOrdenesSIPOVWsServiceSOAP"), ConsultarOrdenesSIPOVWsServiceSOAP.class, features);
    }

    /**
     * 
     * @return
     *     returns ConsultarOrdenesSIPOVWsServiceSOAP
     */
    @WebEndpoint(name = "ConsultarOrdenesSIPOVWsServiceSOAP1")
    public ConsultarOrdenesSIPOVWsServiceSOAP getConsultarOrdenesSIPOVWsServiceSOAP1() {
        return super.getPort(new QName("http://tempuri.org/", "ConsultarOrdenesSIPOVWsServiceSOAP1"), ConsultarOrdenesSIPOVWsServiceSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarOrdenesSIPOVWsServiceSOAP
     */
    @WebEndpoint(name = "ConsultarOrdenesSIPOVWsServiceSOAP1")
    public ConsultarOrdenesSIPOVWsServiceSOAP getConsultarOrdenesSIPOVWsServiceSOAP1(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ConsultarOrdenesSIPOVWsServiceSOAP1"), ConsultarOrdenesSIPOVWsServiceSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARORDENESSIPOV_EXCEPTION!= null) {
            throw CONSULTARORDENESSIPOV_EXCEPTION;
        }
        return CONSULTARORDENESSIPOV_WSDL_LOCATION;
    }

}
