
package org.tempuri.srvIntConsultaEventos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wcf_DAICMA_Eventos", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.30.26.16:1111/wcf_DAICMA_Eventos.svc?wsdl")
public class WcfDAICMAEventos
    extends Service
{

    private final static URL WCFDAICMAEVENTOS_WSDL_LOCATION;
    private final static WebServiceException WCFDAICMAEVENTOS_EXCEPTION;
    private final static QName WCFDAICMAEVENTOS_QNAME = new QName("http://tempuri.org/", "wcf_DAICMA_Eventos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("http://213.136.81.75:8888/wcf_DAICMA_Eventos.svc?wsdl");
            url = new URL("http://172.30.26.16:1111/wcf_DAICMA_Eventos.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WCFDAICMAEVENTOS_WSDL_LOCATION = url;
        WCFDAICMAEVENTOS_EXCEPTION = e;
    }

    public WcfDAICMAEventos() {
        super(__getWsdlLocation(), WCFDAICMAEVENTOS_QNAME);
    }

    public WcfDAICMAEventos(WebServiceFeature... features) {
        super(__getWsdlLocation(), WCFDAICMAEVENTOS_QNAME, features);
    }

    public WcfDAICMAEventos(URL wsdlLocation) {
        super(wsdlLocation, WCFDAICMAEVENTOS_QNAME);
    }

    public WcfDAICMAEventos(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WCFDAICMAEVENTOS_QNAME, features);
    }

    public WcfDAICMAEventos(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WcfDAICMAEventos(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IwcfDAICMAEventos
     */
    @WebEndpoint(name = "BasicHttpBinding_Iwcf_DAICMA_Eventos")
    public IwcfDAICMAEventos getBasicHttpBindingIwcfDAICMAEventos() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_Iwcf_DAICMA_Eventos"), IwcfDAICMAEventos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IwcfDAICMAEventos
     */
    @WebEndpoint(name = "BasicHttpBinding_Iwcf_DAICMA_Eventos")
    public IwcfDAICMAEventos getBasicHttpBindingIwcfDAICMAEventos(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_Iwcf_DAICMA_Eventos"), IwcfDAICMAEventos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WCFDAICMAEVENTOS_EXCEPTION!= null) {
            throw WCFDAICMAEVENTOS_EXCEPTION;
        }
        return WCFDAICMAEVENTOS_WSDL_LOCATION;
    }

}
