
package org.tempuri.operaciones;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wcf_DAICMA_Operaciones", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.30.26.16:1112/wcf_DAICMA_Operaciones.svc?wsdl")
public class WcfDAICMAOperaciones
    extends Service
{

    private final static URL WCFDAICMAOPERACIONES_WSDL_LOCATION;
    private final static WebServiceException WCFDAICMAOPERACIONES_EXCEPTION;
    private final static QName WCFDAICMAOPERACIONES_QNAME = new QName("http://tempuri.org/", "wcf_DAICMA_Operaciones");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("http://213.136.81.75:8889/wcf_DAICMA_Operaciones.svc?wsdl");
            url = new URL("http://172.30.26.16:1112/wcf_DAICMA_Operaciones.svc?wsdl");
            
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WCFDAICMAOPERACIONES_WSDL_LOCATION = url;
        WCFDAICMAOPERACIONES_EXCEPTION = e;
    }

    public WcfDAICMAOperaciones() {
        super(__getWsdlLocation(), WCFDAICMAOPERACIONES_QNAME);
    }

    public WcfDAICMAOperaciones(WebServiceFeature... features) {
        super(__getWsdlLocation(), WCFDAICMAOPERACIONES_QNAME, features);
    }

    public WcfDAICMAOperaciones(URL wsdlLocation) {
        super(wsdlLocation, WCFDAICMAOPERACIONES_QNAME);
    }

    public WcfDAICMAOperaciones(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WCFDAICMAOPERACIONES_QNAME, features);
    }

    public WcfDAICMAOperaciones(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WcfDAICMAOperaciones(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IwcfDAICMAOperaciones
     */
    @WebEndpoint(name = "BasicHttpBinding_Iwcf_DAICMA_Operaciones")
    public IwcfDAICMAOperaciones getBasicHttpBindingIwcfDAICMAOperaciones() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_Iwcf_DAICMA_Operaciones"), IwcfDAICMAOperaciones.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IwcfDAICMAOperaciones
     */
    @WebEndpoint(name = "BasicHttpBinding_Iwcf_DAICMA_Operaciones")
    public IwcfDAICMAOperaciones getBasicHttpBindingIwcfDAICMAOperaciones(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_Iwcf_DAICMA_Operaciones"), IwcfDAICMAOperaciones.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WCFDAICMAOPERACIONES_EXCEPTION!= null) {
            throw WCFDAICMAOPERACIONES_EXCEPTION;
        }
        return WCFDAICMAOPERACIONES_WSDL_LOCATION;
    }

}
