
package co.com.ubi.enviarpdfcertificadolibertad;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnviarPDFCertificadoLibertad", targetNamespace = "http://enviarPDFCertificadoLibertad.ubi.com.co/", wsdlLocation = "http://172.30.75.10:7010/ServicioEnviarPDFCertificadoLibertad/EnviarPDFCertificadoLibertad?wsdl")
public class EnviarPDFCertificadoLibertad_Service
    extends Service
{

    private final static URL ENVIARPDFCERTIFICADOLIBERTAD_WSDL_LOCATION;
    private final static WebServiceException ENVIARPDFCERTIFICADOLIBERTAD_EXCEPTION;
    private final static QName ENVIARPDFCERTIFICADOLIBERTAD_QNAME = new QName("http://enviarPDFCertificadoLibertad.ubi.com.co/", "EnviarPDFCertificadoLibertad");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.75.10:7010/ServicioEnviarPDFCertificadoLibertad/EnviarPDFCertificadoLibertad?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENVIARPDFCERTIFICADOLIBERTAD_WSDL_LOCATION = url;
        ENVIARPDFCERTIFICADOLIBERTAD_EXCEPTION = e;
    }

    public EnviarPDFCertificadoLibertad_Service() {
        super(__getWsdlLocation(), ENVIARPDFCERTIFICADOLIBERTAD_QNAME);
    }

    public EnviarPDFCertificadoLibertad_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENVIARPDFCERTIFICADOLIBERTAD_QNAME, features);
    }

    public EnviarPDFCertificadoLibertad_Service(URL wsdlLocation) {
        super(wsdlLocation, ENVIARPDFCERTIFICADOLIBERTAD_QNAME);
    }

    public EnviarPDFCertificadoLibertad_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENVIARPDFCERTIFICADOLIBERTAD_QNAME, features);
    }

    public EnviarPDFCertificadoLibertad_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnviarPDFCertificadoLibertad_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnviarPDFCertificadoLibertad
     */
    @WebEndpoint(name = "EnviarPDFCertificadoLibertadPort")
    public EnviarPDFCertificadoLibertad getEnviarPDFCertificadoLibertadPort() {
        return super.getPort(new QName("http://enviarPDFCertificadoLibertad.ubi.com.co/", "EnviarPDFCertificadoLibertadPort"), EnviarPDFCertificadoLibertad.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnviarPDFCertificadoLibertad
     */
    @WebEndpoint(name = "EnviarPDFCertificadoLibertadPort")
    public EnviarPDFCertificadoLibertad getEnviarPDFCertificadoLibertadPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://enviarPDFCertificadoLibertad.ubi.com.co/", "EnviarPDFCertificadoLibertadPort"), EnviarPDFCertificadoLibertad.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENVIARPDFCERTIFICADOLIBERTAD_EXCEPTION!= null) {
            throw ENVIARPDFCERTIFICADOLIBERTAD_EXCEPTION;
        }
        return ENVIARPDFCERTIFICADOLIBERTAD_WSDL_LOCATION;
    }

}
