
package co.com.ubi.enviarpdfcertificadolibertad;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnviarPDFCertificadoLibertad", targetNamespace = "http://enviarPDFCertificadoLibertad.ubi.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnviarPDFCertificadoLibertad {


    /**
     * 
     * @param entrada
     * @return
     *     returns co.com.ubi.enviarpdfcertificadolibertad.CertificadoLibertadPDFSal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerPDF", targetNamespace = "http://enviarPDFCertificadoLibertad.ubi.com.co/", className = "co.com.ubi.enviarpdfcertificadolibertad.ObtenerPDF")
    @ResponseWrapper(localName = "obtenerPDFResponse", targetNamespace = "http://enviarPDFCertificadoLibertad.ubi.com.co/", className = "co.com.ubi.enviarpdfcertificadolibertad.ObtenerPDFResponse")
    @Action(input = "http://enviarPDFCertificadoLibertad.ubi.com.co/EnviarPDFCertificadoLibertad/obtenerPDFRequest", output = "http://enviarPDFCertificadoLibertad.ubi.com.co/EnviarPDFCertificadoLibertad/obtenerPDFResponse")
    public CertificadoLibertadPDFSal obtenerPDF(
        @WebParam(name = "entrada", targetNamespace = "")
        CertificadoLibertadPDFEnt entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns co.com.ubi.enviarpdfcertificadolibertad.ConsultarCertificadoSal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarPDFPorPin", targetNamespace = "http://enviarPDFCertificadoLibertad.ubi.com.co/", className = "co.com.ubi.enviarpdfcertificadolibertad.ConsultarPDFPorPin")
    @ResponseWrapper(localName = "consultarPDFPorPinResponse", targetNamespace = "http://enviarPDFCertificadoLibertad.ubi.com.co/", className = "co.com.ubi.enviarpdfcertificadolibertad.ConsultarPDFPorPinResponse")
    @Action(input = "http://enviarPDFCertificadoLibertad.ubi.com.co/EnviarPDFCertificadoLibertad/consultarPDFPorPinRequest", output = "http://enviarPDFCertificadoLibertad.ubi.com.co/EnviarPDFCertificadoLibertad/consultarPDFPorPinResponse")
    public ConsultarCertificadoSal consultarPDFPorPin(
        @WebParam(name = "entrada", targetNamespace = "")
        ConsultarCertificadoEnt entrada);

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ejecutarCopiaArchivosCTL", targetNamespace = "http://enviarPDFCertificadoLibertad.ubi.com.co/", className = "co.com.ubi.enviarpdfcertificadolibertad.EjecutarCopiaArchivosCTL")
    @ResponseWrapper(localName = "ejecutarCopiaArchivosCTLResponse", targetNamespace = "http://enviarPDFCertificadoLibertad.ubi.com.co/", className = "co.com.ubi.enviarpdfcertificadolibertad.EjecutarCopiaArchivosCTLResponse")
    @Action(input = "http://enviarPDFCertificadoLibertad.ubi.com.co/EnviarPDFCertificadoLibertad/ejecutarCopiaArchivosCTLRequest", output = "http://enviarPDFCertificadoLibertad.ubi.com.co/EnviarPDFCertificadoLibertad/ejecutarCopiaArchivosCTLResponse")
    public Boolean ejecutarCopiaArchivosCTL();

}
