
package com.koghi.nodo.snr.WSDL.srvIntConsultarDatosBasicos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioConsultaCertificadoTradicion", targetNamespace = "http://glass.aac.step.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioConsultaCertificadoTradicion {


    /**
     * 
     * @param clave
     * @param entrada
     * @param sistemaUsuario
     * @return
     *     returns com.koghi.nodo.snr.WSDL.srvIntConsultarDatosBasicos.TipoCertificadoTradiciLibertSal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ejecutar", targetNamespace = "http://glass.aac.step.org/", className = "com.koghi.nodo.snr.WSDL.srvIntConsultarDatosBasicos.Ejecutar")
    @ResponseWrapper(localName = "ejecutarResponse", targetNamespace = "http://glass.aac.step.org/", className = "com.koghi.nodo.snr.WSDL.srvIntConsultarDatosBasicos.EjecutarResponse")
    @Action(input = "http://glass.aac.step.org/ServicioConsultaCertificadoTradicion/ejecutarRequest", output = "http://glass.aac.step.org/ServicioConsultaCertificadoTradicion/ejecutarResponse")
    public TipoCertificadoTradiciLibertSal ejecutar(
        @WebParam(name = "entrada", targetNamespace = "")
        TipoLstCertificadoTradiciLibertEnt entrada,
        @WebParam(name = "sistemaUsuario", targetNamespace = "")
        String sistemaUsuario,
        @WebParam(name = "clave", targetNamespace = "")
        String clave);

}
