
package com.koghi.nodo.snr.WSDL.srvIntConsultarDatosBasicos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioConsultaCertificadoTradicion", targetNamespace = "http://glass.aac.step.org/", wsdlLocation = "http://172.30.75.11:7010/ServicioConsultaCertificadoTradicion/ServicioConsultaCertificadoTradicion?wsdl")
public class ServicioConsultaCertificadoTradicion_Service
    extends Service
{

    private final static URL SERVICIOCONSULTACERTIFICADOTRADICION_WSDL_LOCATION;
    private final static WebServiceException SERVICIOCONSULTACERTIFICADOTRADICION_EXCEPTION;
    private final static QName SERVICIOCONSULTACERTIFICADOTRADICION_QNAME = new QName("http://glass.aac.step.org/", "ServicioConsultaCertificadoTradicion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.75.11:7010/ServicioConsultaCertificadoTradicion/ServicioConsultaCertificadoTradicion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOCONSULTACERTIFICADOTRADICION_WSDL_LOCATION = url;
        SERVICIOCONSULTACERTIFICADOTRADICION_EXCEPTION = e;
    }

    public ServicioConsultaCertificadoTradicion_Service() {
        super(__getWsdlLocation(), SERVICIOCONSULTACERTIFICADOTRADICION_QNAME);
    }

    public ServicioConsultaCertificadoTradicion_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOCONSULTACERTIFICADOTRADICION_QNAME, features);
    }

    public ServicioConsultaCertificadoTradicion_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOCONSULTACERTIFICADOTRADICION_QNAME);
    }

    public ServicioConsultaCertificadoTradicion_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOCONSULTACERTIFICADOTRADICION_QNAME, features);
    }

    public ServicioConsultaCertificadoTradicion_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioConsultaCertificadoTradicion_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioConsultaCertificadoTradicion
     */
    @WebEndpoint(name = "ServicioConsultaCertificadoTradicionPort")
    public ServicioConsultaCertificadoTradicion getServicioConsultaCertificadoTradicionPort() {
        return super.getPort(new QName("http://glass.aac.step.org/", "ServicioConsultaCertificadoTradicionPort"), ServicioConsultaCertificadoTradicion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioConsultaCertificadoTradicion
     */
    @WebEndpoint(name = "ServicioConsultaCertificadoTradicionPort")
    public ServicioConsultaCertificadoTradicion getServicioConsultaCertificadoTradicionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://glass.aac.step.org/", "ServicioConsultaCertificadoTradicionPort"), ServicioConsultaCertificadoTradicion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOCONSULTACERTIFICADOTRADICION_EXCEPTION!= null) {
            throw SERVICIOCONSULTACERTIFICADOTRADICION_EXCEPTION;
        }
        return SERVICIOCONSULTACERTIFICADOTRADICION_WSDL_LOCATION;
    }

}
