
package com.koghi.nodo.snr.WSDL.srvIntConsultaIndicePropietarioActual;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioConsultaBusquedaParametros", targetNamespace = "http://glass.aac.step.org/", wsdlLocation = "http://172.30.75.11:7010/ServicioConsultaBusquedaParametros/ServicioConsultaBusquedaParametros?wsdl")
public class ServicioConsultaBusquedaParametros_Service
    extends Service
{

    private final static URL SERVICIOCONSULTABUSQUEDAPARAMETROS_WSDL_LOCATION;
    private final static WebServiceException SERVICIOCONSULTABUSQUEDAPARAMETROS_EXCEPTION;
    private final static QName SERVICIOCONSULTABUSQUEDAPARAMETROS_QNAME = new QName("http://glass.aac.step.org/", "ServicioConsultaBusquedaParametros");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.75.11:7010/ServicioConsultaBusquedaParametros/ServicioConsultaBusquedaParametros?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOCONSULTABUSQUEDAPARAMETROS_WSDL_LOCATION = url;
        SERVICIOCONSULTABUSQUEDAPARAMETROS_EXCEPTION = e;
    }

    public ServicioConsultaBusquedaParametros_Service() {
        super(__getWsdlLocation(), SERVICIOCONSULTABUSQUEDAPARAMETROS_QNAME);
    }

    public ServicioConsultaBusquedaParametros_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOCONSULTABUSQUEDAPARAMETROS_QNAME, features);
    }

    public ServicioConsultaBusquedaParametros_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOCONSULTABUSQUEDAPARAMETROS_QNAME);
    }

    public ServicioConsultaBusquedaParametros_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOCONSULTABUSQUEDAPARAMETROS_QNAME, features);
    }

    public ServicioConsultaBusquedaParametros_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioConsultaBusquedaParametros_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioConsultaBusquedaParametros
     */
    @WebEndpoint(name = "ServicioConsultaBusquedaParametrosPort")
    public ServicioConsultaBusquedaParametros getServicioConsultaBusquedaParametrosPort() {
        return super.getPort(new QName("http://glass.aac.step.org/", "ServicioConsultaBusquedaParametrosPort"), ServicioConsultaBusquedaParametros.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioConsultaBusquedaParametros
     */
    @WebEndpoint(name = "ServicioConsultaBusquedaParametrosPort")
    public ServicioConsultaBusquedaParametros getServicioConsultaBusquedaParametrosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://glass.aac.step.org/", "ServicioConsultaBusquedaParametrosPort"), ServicioConsultaBusquedaParametros.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOCONSULTABUSQUEDAPARAMETROS_EXCEPTION!= null) {
            throw SERVICIOCONSULTABUSQUEDAPARAMETROS_EXCEPTION;
        }
        return SERVICIOCONSULTABUSQUEDAPARAMETROS_WSDL_LOCATION;
    }

}
