
package co.gov.rnec.ani.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSConsultas", targetNamespace = "http://ws.ani.rnec.gov.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSConsultas {


    /**
     * 
     * @param cedulas
     * @param entidad
     * @param contrasena
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarCedulas", targetNamespace = "http://ws.ani.rnec.gov.co/", className = "co.gov.rnec.ani.ws.ConsultarCedulas")
    @ResponseWrapper(localName = "consultarCedulasResponse", targetNamespace = "http://ws.ani.rnec.gov.co/", className = "co.gov.rnec.ani.ws.ConsultarCedulasResponse")
    @Action(input = "http://ws.ani.rnec.gov.co/WSConsultas/consultarCedulasRequest", output = "http://ws.ani.rnec.gov.co/WSConsultas/consultarCedulasResponse")
    public String consultarCedulas(
        @WebParam(name = "cedulas", targetNamespace = "")
        String cedulas,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena,
        @WebParam(name = "entidad", targetNamespace = "")
        String entidad,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario);

}
