
package com.onesystem.edatel.catastro.sp.nodotierras;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NodoTierrasWS", targetNamespace = "http://nodotierras.sp.catastro.edatel.onesystem.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NodoTierrasWS {


    /**
     * 
     * @param numeroPredialNacional
     * @param matriculaCompleta
     * @param identificadorEntidad
     * @param fichaPredial
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarCertificadoPredialNodoTierras", targetNamespace = "http://nodotierras.sp.catastro.edatel.onesystem.com/", className = "com.onesystem.edatel.catastro.sp.nodotierras.GenerarCertificadoPredialNodoTierras")
    @ResponseWrapper(localName = "generarCertificadoPredialNodoTierrasResponse", targetNamespace = "http://nodotierras.sp.catastro.edatel.onesystem.com/", className = "com.onesystem.edatel.catastro.sp.nodotierras.GenerarCertificadoPredialNodoTierrasResponse")
    @Action(input = "http://nodotierras.sp.catastro.edatel.onesystem.com/NodoTierrasWS/generarCertificadoPredialNodoTierrasRequest", output = "http://nodotierras.sp.catastro.edatel.onesystem.com/NodoTierrasWS/generarCertificadoPredialNodoTierrasResponse")
    public String generarCertificadoPredialNodoTierras(
        @WebParam(name = "fichaPredial", targetNamespace = "")
        String fichaPredial,
        @WebParam(name = "matriculaCompleta", targetNamespace = "")
        String matriculaCompleta,
        @WebParam(name = "numeroPredialNacional", targetNamespace = "")
        String numeroPredialNacional,
        @WebParam(name = "identificadorEntidad", targetNamespace = "")
        int identificadorEntidad);

    /**
     * 
     * @param nombrePropietario
     * @param tipoDocumento
     * @param numeroDocumento
     * @param identificadorEntidad
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "genCertPoseerNoPoseerNodoTierras", targetNamespace = "http://nodotierras.sp.catastro.edatel.onesystem.com/", className = "com.onesystem.edatel.catastro.sp.nodotierras.GenCertPoseerNoPoseerNodoTierras")
    @ResponseWrapper(localName = "genCertPoseerNoPoseerNodoTierrasResponse", targetNamespace = "http://nodotierras.sp.catastro.edatel.onesystem.com/", className = "com.onesystem.edatel.catastro.sp.nodotierras.GenCertPoseerNoPoseerNodoTierrasResponse")
    @Action(input = "http://nodotierras.sp.catastro.edatel.onesystem.com/NodoTierrasWS/genCertPoseerNoPoseerNodoTierrasRequest", output = "http://nodotierras.sp.catastro.edatel.onesystem.com/NodoTierrasWS/genCertPoseerNoPoseerNodoTierrasResponse")
    public String genCertPoseerNoPoseerNodoTierras(
        @WebParam(name = "tipoDocumento", targetNamespace = "")
        String tipoDocumento,
        @WebParam(name = "numeroDocumento", targetNamespace = "")
        String numeroDocumento,
        @WebParam(name = "nombrePropietario", targetNamespace = "")
        String nombrePropietario,
        @WebParam(name = "identificadorEntidad", targetNamespace = "")
        int identificadorEntidad);

    /**
     * 
     * @param numeroPredialNacional
     * @param matriculaCompleta
     * @param identificadorEntidad
     * @param fichaPredial
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "genCertPlanoCatastralNodoTierras", targetNamespace = "http://nodotierras.sp.catastro.edatel.onesystem.com/", className = "com.onesystem.edatel.catastro.sp.nodotierras.GenCertPlanoCatastralNodoTierras")
    @ResponseWrapper(localName = "genCertPlanoCatastralNodoTierrasResponse", targetNamespace = "http://nodotierras.sp.catastro.edatel.onesystem.com/", className = "com.onesystem.edatel.catastro.sp.nodotierras.GenCertPlanoCatastralNodoTierrasResponse")
    @Action(input = "http://nodotierras.sp.catastro.edatel.onesystem.com/NodoTierrasWS/genCertPlanoCatastralNodoTierrasRequest", output = "http://nodotierras.sp.catastro.edatel.onesystem.com/NodoTierrasWS/genCertPlanoCatastralNodoTierrasResponse")
    public String genCertPlanoCatastralNodoTierras(
        @WebParam(name = "fichaPredial", targetNamespace = "")
        String fichaPredial,
        @WebParam(name = "matriculaCompleta", targetNamespace = "")
        String matriculaCompleta,
        @WebParam(name = "numeroPredialNacional", targetNamespace = "")
        String numeroPredialNacional,
        @WebParam(name = "identificadorEntidad", targetNamespace = "")
        int identificadorEntidad);

    /**
     * 
     * @param nombrePropietario
     * @param tipoDocumento
     * @param razonSocial
     * @param numeroPredialNacional
     * @param numeroDocumento
     * @param matriculaCompleta
     * @param identificadorEntidad
     * @param fichaPredial
     * @return
     *     returns java.util.List<com.onesystem.edatel.catastro.sp.nodotierras.InfoPredio>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerInformacionPredialNodoTierras", targetNamespace = "http://nodotierras.sp.catastro.edatel.onesystem.com/", className = "com.onesystem.edatel.catastro.sp.nodotierras.ObtenerInformacionPredialNodoTierras")
    @ResponseWrapper(localName = "obtenerInformacionPredialNodoTierrasResponse", targetNamespace = "http://nodotierras.sp.catastro.edatel.onesystem.com/", className = "com.onesystem.edatel.catastro.sp.nodotierras.ObtenerInformacionPredialNodoTierrasResponse")
    @Action(input = "http://nodotierras.sp.catastro.edatel.onesystem.com/NodoTierrasWS/obtenerInformacionPredialNodoTierrasRequest", output = "http://nodotierras.sp.catastro.edatel.onesystem.com/NodoTierrasWS/obtenerInformacionPredialNodoTierrasResponse")
    public List<InfoPredio> obtenerInformacionPredialNodoTierras(
        @WebParam(name = "tipoDocumento", targetNamespace = "")
        String tipoDocumento,
        @WebParam(name = "numeroDocumento", targetNamespace = "")
        String numeroDocumento,
        @WebParam(name = "matriculaCompleta", targetNamespace = "")
        String matriculaCompleta,
        @WebParam(name = "razonSocial", targetNamespace = "")
        String razonSocial,
        @WebParam(name = "nombrePropietario", targetNamespace = "")
        String nombrePropietario,
        @WebParam(name = "numeroPredialNacional", targetNamespace = "")
        String numeroPredialNacional,
        @WebParam(name = "fichaPredial", targetNamespace = "")
        String fichaPredial,
        @WebParam(name = "identificadorEntidad", targetNamespace = "")
        int identificadorEntidad);

}
