//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.30 at 12:20:45 PM COT 
//


package co.com.ubi.servgenpdfconsultaj;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.com.ubi.servgenpdfconsultaj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObtenerConsultaJuridica_QNAME = new QName("http://servgenpdfconsultaj.ubi.com.co/", "obtenerConsultaJuridica");
    private final static QName _ObtenerConsultaJuridicaResponse_QNAME = new QName("http://servgenpdfconsultaj.ubi.com.co/", "obtenerConsultaJuridicaResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.com.ubi.servgenpdfconsultaj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObtenerConsultaJuridicaResponse }
     * 
     */
    public ObtenerConsultaJuridicaResponse createObtenerConsultaJuridicaResponse() {
        return new ObtenerConsultaJuridicaResponse();
    }

    /**
     * Create an instance of {@link ObtenerConsultaJuridica }
     * 
     */
    public ObtenerConsultaJuridica createObtenerConsultaJuridica() {
        return new ObtenerConsultaJuridica();
    }

    /**
     * Create an instance of {@link SalidaServGenPDFConsultaJuridica }
     * 
     */
    public SalidaServGenPDFConsultaJuridica createSalidaServGenPDFConsultaJuridica() {
        return new SalidaServGenPDFConsultaJuridica();
    }

    /**
     * Create an instance of {@link TipoLogResultadoConsulta }
     * 
     */
    public TipoLogResultadoConsulta createTipoLogResultadoConsulta() {
        return new TipoLogResultadoConsulta();
    }

    /**
     * Create an instance of {@link EntradaServGenPDFConsultaJuridica }
     * 
     */
    public EntradaServGenPDFConsultaJuridica createEntradaServGenPDFConsultaJuridica() {
        return new EntradaServGenPDFConsultaJuridica();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerConsultaJuridica }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servgenpdfconsultaj.ubi.com.co/", name = "obtenerConsultaJuridica")
    public JAXBElement<ObtenerConsultaJuridica> createObtenerConsultaJuridica(ObtenerConsultaJuridica value) {
        return new JAXBElement<ObtenerConsultaJuridica>(_ObtenerConsultaJuridica_QNAME, ObtenerConsultaJuridica.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerConsultaJuridicaResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servgenpdfconsultaj.ubi.com.co/", name = "obtenerConsultaJuridicaResponse")
    public JAXBElement<ObtenerConsultaJuridicaResponse> createObtenerConsultaJuridicaResponse(ObtenerConsultaJuridicaResponse value) {
        return new JAXBElement<ObtenerConsultaJuridicaResponse>(_ObtenerConsultaJuridicaResponse_QNAME, ObtenerConsultaJuridicaResponse.class, null, value);
    }

}
