//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.30 at 12:20:45 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://servgenpdfconsultaj.ubi.com.co/")
package co.com.ubi.servgenpdfconsultaj;
