
package co.com.ubi.servgenpdfconsultaj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioGeneraPDFConsultaJuridica", targetNamespace = "http://servgenpdfconsultaj.ubi.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioGeneraPDFConsultaJuridica {


    /**
     * 
     * @param entrada
     * @return
     *     returns co.com.ubi.servgenpdfconsultaj.SalidaServGenPDFConsultaJuridica
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerConsultaJuridica", targetNamespace = "http://servgenpdfconsultaj.ubi.com.co/", className = "co.com.ubi.servgenpdfconsultaj.ObtenerConsultaJuridica")
    @ResponseWrapper(localName = "obtenerConsultaJuridicaResponse", targetNamespace = "http://servgenpdfconsultaj.ubi.com.co/", className = "co.com.ubi.servgenpdfconsultaj.ObtenerConsultaJuridicaResponse")
    @Action(input = "http://servgenpdfconsultaj.ubi.com.co/ServicioGeneraPDFConsultaJuridica/obtenerConsultaJuridicaRequest", output = "http://servgenpdfconsultaj.ubi.com.co/ServicioGeneraPDFConsultaJuridica/obtenerConsultaJuridicaResponse")
    public SalidaServGenPDFConsultaJuridica obtenerConsultaJuridica(
        @WebParam(name = "entrada", targetNamespace = "")
        EntradaServGenPDFConsultaJuridica entrada);

}
