
package com.onesystem.edatel.catastro.sp.nodotierras;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NodoTierrasWS", targetNamespace = "http://nodotierras.sp.catastro.edatel.onesystem.com/", wsdlLocation = "http://10.0.68.163:28082/NodoTierras-context-root/NodoTierrasWS?WSDL")
public class NodoTierrasWS_Service
    extends Service
{

    private final static URL NODOTIERRASWS_WSDL_LOCATION;
    private final static WebServiceException NODOTIERRASWS_EXCEPTION;
    private final static QName NODOTIERRASWS_QNAME = new QName("http://nodotierras.sp.catastro.edatel.onesystem.com/", "NodoTierrasWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.68.163:28082/NodoTierras-context-root/NodoTierrasWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NODOTIERRASWS_WSDL_LOCATION = url;
        NODOTIERRASWS_EXCEPTION = e;
    }

    public NodoTierrasWS_Service() {
        super(__getWsdlLocation(), NODOTIERRASWS_QNAME);
    }

    public NodoTierrasWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NODOTIERRASWS_QNAME, features);
    }

    public NodoTierrasWS_Service(URL wsdlLocation) {
        super(wsdlLocation, NODOTIERRASWS_QNAME);
    }

    public NodoTierrasWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NODOTIERRASWS_QNAME, features);
    }

    public NodoTierrasWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NodoTierrasWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NodoTierrasWS
     */
    @WebEndpoint(name = "NodoTierrasWSPort")
    public NodoTierrasWS getNodoTierrasWSPort() {
        return super.getPort(new QName("http://nodotierras.sp.catastro.edatel.onesystem.com/", "NodoTierrasWSPort"), NodoTierrasWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NodoTierrasWS
     */
    @WebEndpoint(name = "NodoTierrasWSPort")
    public NodoTierrasWS getNodoTierrasWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://nodotierras.sp.catastro.edatel.onesystem.com/", "NodoTierrasWSPort"), NodoTierrasWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NODOTIERRASWS_EXCEPTION!= null) {
            throw NODOTIERRASWS_EXCEPTION;
        }
        return NODOTIERRASWS_WSDL_LOCATION;
    }

}
